jwt:
  secret: asdsadaad23r324yf214uyf12fo21y4ft21f421uf4yu12f412asdsadaad23r324yf214uyf12fo21y4ft21f421uf4yu12f412asdsadaad23r324yf214uyf12fo21y4ft21f421uf4yu12f412asdsadaad23r324yf214uyf12fo21y4ft21f421uf4yu12f412

server:
  ssl:
    key-store: classpath:keystore/keystore.jks
    key-store-password: qwerty
    key-store-type: JKS
    key-password: qwerty
spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  security:

  mail:
    host: smtp-relay.brevo.com
    port: 587
    username: aryemfedorov@gmail.com
    password: 0LCYqR1IE4c76mBW
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  allowed-cors: https://localhost:5173

aws:
  region: eu-north-1
  access_key: AKIAQ3EGTR3EFKYW4DEE
  secret_access_key: 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
  bucket-name: flowers-ua
#    oauth2:
#      client:
#        registration:
#          google:
#            client-id: 244221050743-6dpueh5dal4v3kblf0tesfp4m6dgmqie.apps.googleusercontent.com
#            client-secret: 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
#logging:
#  level:
#    org.springframework.security.web.csrf: debug


