jwt:
  secret: asdsadaad23r324yf214uyf12fo21y4ft21f421uf4yu12f412asdsadaad23r324yf214uyf12fo21y4ft21f421uf4yu12f412asdsadaad23r324yf214uyf12fo21y4ft21f421uf4yu12f412asdsadaad23r324yf214uyf12fo21y4ft21f421uf4yu12f412

server:
  ssl:
    key-store: classpath:keystore/keystore.jks
    key-store-password: qwerty
    key-store-type: JKS
    key-password: qwerty
spring:
  security:

  mail:
    host: smtp-relay.brevo.com
    port: 587
    username: aryemfedorov@gmail.com
    password: 0LCYqR1IE4c76mBW
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  allowed-cors: https://localhost:5173

aws:
  region: eu-north-1
  access_key: AKIA5Q2A6DOFL6W4K37Z
  secret_access_key: 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
  bucket-name: flowers-ua
#    oauth2:
#      client:
#        registration:
#          google:
#            client-id: 244221050743-6dpueh5dal4v3kblf0tesfp4m6dgmqie.apps.googleusercontent.com
#            client-secret: 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
#logging:
#  level:
#    org.springframework.security.web.csrf: debug


